In [1]:
import torch
print(torch.__version__)

1.7.0


In [2]:
x = torch.tensor([[1, 2]])
y = torch.tensor([[1], [2]])

In [3]:
print(x.size())

torch.Size([1, 2])


In [4]:
print(x.shape)

torch.Size([1, 2])


In [5]:
print(y.size())

torch.Size([2, 1])


In [6]:
print(x.dtype)

torch.int64


In [7]:
x = torch.tensor([False, 1, 2.0])

In [8]:
print(x)

tensor([0., 1., 2.])


In [9]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[3, 5, 2, 3],
        [6, 2, 6, 2],
        [6, 4, 1, 5]])

In [12]:
torch.rand(3,4)

tensor([[0.4319, 0.5457, 0.2080, 0.6183],
        [0.0917, 0.5232, 0.9067, 0.9183],
        [0.1109, 0.2018, 0.7303, 0.4546]])

In [13]:
torch.randn((3,4))

tensor([[ 0.0805,  1.2187,  0.0338,  1.0819],
        [-0.2336,  0.0883, -0.5053,  1.7707],
        [ 0.1411,  0.4116,  0.7928,  0.2057]])

In [14]:
import numpy as np

In [15]:
x = np.array([[10, 20, 30], [2, 3, 4]])
y = torch.tensor(x)
z = torch.from_numpy(x)
print(type(x), type(y), type(z))

<class 'numpy.ndarray'> <class 'torch.Tensor'> <class 'torch.Tensor'>


In [16]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x * 10)

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])


In [17]:
y = x.add(10)

In [18]:
print(y)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])


In [19]:
y = torch.tensor([2, 3, 1, 0])

In [20]:
y = y.view(4, 1)

In [21]:
y.shape

torch.Size([4, 1])

In [22]:
x = torch.randn(10, 1, 10)
z1 = torch.squeeze(x, 1)
z2 = x.squeeze(1)
assert torch.all(z1 == z2)

In [23]:
print('Squeeze:\n', x.shape, z1.shape)

Squeeze:
 torch.Size([10, 1, 10]) torch.Size([10, 10])


In [24]:
x = torch.randn(10, 10)
print(x.shape)
z1 = x.unsqueeze(0)
print(z1.shape)

z2, z3, z4 = x[None], x[:, None], x[:, :, None]
print(z2.shape, z3.shape, z4.shape)

torch.Size([10, 10])
torch.Size([1, 10, 10])
torch.Size([1, 10, 10]) torch.Size([10, 1, 10]) torch.Size([10, 10, 1])


In [25]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

In [26]:
y

tensor([[2],
        [3],
        [1],
        [0]])

In [27]:
print(torch.matmul(x, y))

tensor([[11],
        [35]])


In [28]:
print(x@y)

tensor([[11],
        [35]])


In [29]:
x = torch.randn(10, 10, 10)

In [30]:
z = torch.cat([x, x], axis=0)

In [31]:
print('Cat axis 0:', x.shape, z.shape)

Cat axis 0: torch.Size([10, 10, 10]) torch.Size([20, 10, 10])


In [32]:
z = torch.cat([x, x], axis=1)
print('Cat axis 1:', x.shape, z.shape)

Cat axis 1: torch.Size([10, 10, 10]) torch.Size([10, 20, 10])


In [34]:
x = torch.arange(25).reshape(5, 5)
print('Max:', x.shape, x.max())

Max: torch.Size([5, 5]) tensor(24)


In [35]:
x.max(dim=0)

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))

In [36]:
m, argm = x.max(dim=1)

In [37]:
print('Max in axis 1:\n', m, argm)

Max in axis 1:
 tensor([ 4,  9, 14, 19, 24]) tensor([4, 4, 4, 4, 4])


In [38]:
x = torch.randn(10, 20, 30)
z = x.permute(2, 0, 1)

In [40]:
print('Permute dimensions:', x.shape, z.shape)

Permute dimensions: torch.Size([10, 20, 30]) torch.Size([30, 10, 20])
