In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[2] = 3

In [3]:
a

[1.0, 2.0, 3]

In [4]:
import torch

In [5]:
a = torch.ones(3)

In [6]:
a

tensor([1., 1., 1.])

In [7]:
a[1]

tensor(1.)

In [8]:
a[2] = 2.0

In [9]:
a

tensor([1., 1., 2.])

In [10]:
points = torch.zeros(6)

In [11]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [13]:
points.shape

torch.Size([3, 2])

In [14]:
points[0,1]

tensor(1.)

In [15]:
double_points = torch.ones(10, 2, dtype=torch.double)

In [16]:
short_points = torch.tensor([[1,2], [3,4]], dtype=torch.short)

In [17]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [18]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [19]:
second_point = points[1]
second_point.storage_offset()

2

In [20]:
second_point.size()

torch.Size([2])

In [21]:
points.stride()

(2, 1)

In [22]:
some_t = torch.ones(3, 4, 5)

In [23]:
transpose_t = some_t.transpose(0, 2)

In [24]:
points_np = points.numpy()
points_np

array([[4., 1.],
       [5., 3.],
       [2., 1.]], dtype=float32)

In [25]:
points = torch.from_numpy(points_np)

In [26]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [27]:
import h5py

In [28]:
f = h5py.File('./ourpoints.hdf5', 'w')

In [29]:
dset = f.create_dataset('coords', data=points.numpy())

In [30]:
f.close()